name: SBOM Generate

description: Generate Software Bill of Materials using Syft.

inputs:

  format:
    description: SBOM output format.
    required: false
    default: cyclonedx-json

  output-file:
    description: Output file path.
    required: false
    default: sbom.json

runs:
  using: composite

  steps:

    - name: Install Syft
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM
      shell: bash
      run: |
        syft dir:. \
          -o ${{ inputs.format }} \
          > ${{ inputs.output-file }}

    - name: Verify SBOM Generated
      shell: bash
      run: |
        ls -lh ${{ inputs.output-file }}