name: Dependency Scan

description: Scan project dependencies for known vulnerabilities.

inputs:

  tech-stack:
    description: Technology stack
    required: true

runs:
  using: composite

  steps:

    # Python

    - name: Install pip-audit
      if: inputs.tech-stack == 'python'
      shell: bash
      run: |
        pip install pip-audit

    - name: Run Python Dependency Scan
      if: inputs.tech-stack == 'python'
      shell: bash
      run: |
        pip-audit

    # NodeJS

    - name: Run NodeJS Dependency Scan
      if: inputs.tech-stack == 'nodejs'
      shell: bash
      run: |
        npm audit --audit-level=high

    # Java

    - name: Run Java Dependency Scan
      if: inputs.tech-stack == 'java'
      shell: bash
      run: |
        mvn org.owasp:dependency-check-maven:check

    # Go

    - name: Install govulncheck
      if: inputs.tech-stack == 'go'
      shell: bash
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run Go Dependency Scan
      if: inputs.tech-stack == 'go'
      shell: bash
      run: |
        govulncheck ./...