name: Secret Scan

description: Scan repository for hardcoded secrets using Gitleaks.

runs:
  using: composite

  steps:

    - name: Install Gitleaks
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Secret Scan
      shell: bash
      run: |
        gitleaks detect --source . --verbose